# Generated by Django 4.2 on 2025-09-05 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clouddiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud Diary',
                'verbose_name_plural': 'Cloud Diaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudDiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clouddiary/images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('clouddiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clouddiary.clouddiary')),
            ],
            options={
                'verbose_name': 'Cloud Diary Image',
                'verbose_name_plural': 'Cloud Diary Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
