# Generated by Django 4.2 on 2025-09-05 03:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouddiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddiaryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
