"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'
# Empty static directory - no custom static files
STATICFILES_DIRS = []  # Removed empty static directory
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production, fallback to insecure key for development only
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-msu85(n(%fr(h9*vcn(3asho7qxkxze3=8b2i2)q2e7+1rgt6(')

# SECURITY WARNING: don't run with debug turned on in production!
# Default to True for development, set DEBUG=False in production via environment variable
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = [
    'olaf-backend.onrender.com', 
    '127.0.0.1', 
    'localhost', 
    '.railway.app',
    '.bolt.app',  # Bolt.new platform
]
# Add additional hosts from environment variable if provided
if os.getenv('ALLOWED_HOST'):
    ALLOWED_HOSTS.extend([host.strip() for host in os.getenv('ALLOWED_HOST').split(',') if host.strip()])


# Application definition

INSTALLED_APPS = [
    # Django Admin removed - using Swagger/OpenAPI documentation instead
    # 'django.contrib.admin',  # Removed - use /api/docs/ for API documentation
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # Required for CSRF token storage
    # 'django.contrib.messages',  # Removed - not used in API-only app
    'django.contrib.staticfiles',

    'rest_framework',
    "corsheaders",
    'rest_framework_simplejwt.token_blacklist',
    'django_bolt',  # Django-Bolt API framework (includes Swagger/OpenAPI)
    'cloudinary',
    "blog",
    "authentication",
    "clouddiary",
    "shared_images"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',  # Required for CSRF
    'mysite.middleware.CustomCommonMiddleware',  # Custom CommonMiddleware to prevent API redirect loops
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',  # Removed - not used
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Keep APPEND_SLASH enabled for general use, but our custom middleware will handle API endpoints
APPEND_SLASH = True

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',  # Removed - not used
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database configuration - supports both individual parameters and connection string
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use connection string (recommended for Neon)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    # Use individual parameters (fallback)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'olaf_backend'),
            'USER': os.getenv('DB_USER', 'zxin'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': 600, # Keep connections open for 10 minutes
            'OPTIONS': {
                'sslmode': 'require',  # Required for Neon
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = False  # Disabled - API-only app doesn't need i18n (saves ~10-20MB)
USE_L10N = False  # Disabled - no localization needed

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://olafs.netlify.app",
    "https://web-production-ba20a.up.railway.app",  # Railway backend domain
]
# Add Railway domain from environment variable
if os.getenv('RAILWAY_PUBLIC_DOMAIN'):
    railway_url = f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN')}"
    if railway_url not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(railway_url)
# Add additional CORS origins from environment variable if provided
if os.getenv('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS').split(',') if origin.strip()])

# Allow credentials for CORS
CORS_ALLOW_CREDENTIALS = True

# Expose headers for frontend access
# Note: Set-Cookie cannot be exposed (it's a forbidden header)
# But we expose other headers that frontend might need
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken", "Access-Control-Allow-Origin", "Access-Control-Allow-Credentials"]

# CSRF Configuration
CSRF_COOKIE_SECURE = not DEBUG  # True in production (HTTPS only)
CSRF_COOKIE_HTTP_ONLY = False  # Allow JavaScript to read for API calls
CSRF_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"  # None for cross-origin in production
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://olafs.netlify.app",
    "https://olaf-backend.onrender.com",
    "https://web-production-ba20a.up.railway.app",  # Railway backend domain
]
# Add Railway domain from environment variable (Django doesn't support wildcards in CSRF_TRUSTED_ORIGINS)
if os.getenv('RAILWAY_PUBLIC_DOMAIN'):
    railway_csrf_url = f"https://{os.getenv('RAILWAY_PUBLIC_DOMAIN')}"
    if railway_csrf_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_csrf_url)
# Add additional trusted origins from environment variable
if os.getenv('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS').split(',') if origin.strip()])

# Session Configuration
SESSION_COOKIE_SECURE = not DEBUG  # True in production
SESSION_COOKIE_HTTP_ONLY = True
SESSION_COOKIE_SAMESITE = "None" if not DEBUG else "Lax"

# Additional CORS settings for better cookie handling
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),

    # Custom cookie settings for JWT tokens
    'AUTH_COOKIE': 'access',
    'AUTH_COOKIE_REFRESH': 'refresh',
    'AUTH_COOKIE_DOMAIN': os.getenv('COOKIE_DOMAIN', None),  # Set via environment variable for Railway
    # Cookie security settings
    # Note: For cross-origin (localhost:3000 -> localhost:8000), we need SameSite=None
    # Chrome allows Secure=False with SameSite=None for localhost in development
    # For development: Secure=False, SameSite=None (works with localhost cross-origin)
    # For production: Secure=True, SameSite=None (for cross-origin)
    # IMPORTANT: When SameSite=None, Secure must be True in production, but Chrome allows False for localhost
    'AUTH_COOKIE_SECURE': os.getenv('COOKIE_SECURE', 'False' if DEBUG else 'True') == 'True',
    'AUTH_COOKIE_HTTP_ONLY': True,  # Prevent XSS attacks
    'AUTH_COOKIE_PATH': '/',
    # Use None for cross-origin support (both dev and prod)
    # Frontend (localhost:3000) and backend (localhost:8000) are different origins
    # Chrome allows Secure=False with SameSite=None for localhost
    'AUTH_COOKIE_SAMESITE': os.getenv('COOKIE_SAMESITE', 'None'),
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication', # TODO: For now
        'authentication.authenticate.CustomAuthentication',
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        'rest_framework.permissions.AllowAny',
    ],
    
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


AUTH_USER_MODEL = "authentication.Account"

# Authentication backends - use custom email backend
AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # Fallback
]

# Cloudinary Configuration
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME', 'your_cloud_name'),
    api_key=os.getenv('CLOUDINARY_API_KEY', 'your_api_key'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET', 'your_api_secret'),
    secure=True
)
