# Generated by Django 5.1.1 on 2024-09-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='header',
        ),
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
