# Generated by Django 4.2 on 2025-09-10 05:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Shared Image',
                'verbose_name_plural': 'Shared Images',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sharedimage',
            index=models.Index(fields=['content_type', 'object_id'], name='shared_imag_content_2564b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedimage',
            index=models.Index(fields=['is_primary'], name='shared_imag_is_prim_b4fd4d_idx'),
        ),
    ]
